name: music_player_app
description: Современный музыкальный плеер
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.15
  audio_service: ^0.18.13
  rxdart: ^0.27.7
  
  # Media
  on_audio_query: ^2.9.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI & Effects
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  liquid_progress_indicator: ^0.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  
  # Plugins
  equalizer_plugin: ^0.2.0
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
