name: music_player_app
description: A modern professional Flutter Music Player.
publish_to: 'none'
version: 1.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.40
  audio_service: ^0.18.11
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
